# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 04:04
from __future__ import unicode_literals

import biblioteca.models
import biblioteca.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metadata_model',
            fields=[
                ('nombre', models.CharField(max_length=25)),
                ('id_organizacion', models.CharField(max_length=25)),
                ('id_app', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('codigo_app', models.CharField(max_length=25)),
                ('version', models.CharField(max_length=25)),
                ('clase_inicial', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='registrar_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargar_app', models.FileField(blank=True, null=True, upload_to=biblioteca.models.generate_path, validators=[biblioteca.validators.valid_extension])),
            ],
        ),
    ]
