# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=60)),
                ('dni', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pro', models.IntegerField()),
                ('nombre_pro', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capa.Profesion'),
        ),
    ]
