# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0002_auto_20160526_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='codigo_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capa.Profesion'),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='codigo_pro',
            field=models.IntegerField(default=13),
        ),
    ]
