# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0003_auto_20160526_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='id',
        ),
        migrations.AlterField(
            model_name='profesion',
            name='codigo_pro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
