# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0004_auto_20160526_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='codigo_pro',
            field=models.IntegerField(),
        ),
    ]
