# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0005_auto_20160526_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='appModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_app', models.CharField(help_text='Codigo de la aplicacion', max_length=12, validators=[django.core.validators.RegexValidator('^[\\d]+$', 'Codigo de aplicacion inv\xe1lido. Solo se permiten numeros')])),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Profesion',
        ),
    ]
