# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 19:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Cédula de Identidad del usuario', max_length=8, validators=[django.core.validators.RegexValidator('^[\\d]{7,8}+$', 'Introduzca un número de cédula válido. Solo se permiten números y una longitud de 7 u 8 carácteres.')])),
                ('canal', models.CharField(help_text='Canal de televisión', max_length=175)),
                ('cargo', models.CharField(help_text='Cargo del usuario', max_length=175)),
                ('telefono', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=20, validators=[django.core.validators.RegexValidator('^[\\d+-]+$', 'Número telefónico inválido. Solo se permiten números, y los signos + o -')])),
                ('user', models.OneToOneField(help_text='Relación entre los datos de registro y el usuario con acceso al sistema', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
